name: Documentation

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main]

# Newer commits should cancel old runs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      # Setup
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: "3.28"
      - name: Install dependencies
        run: |
          sudo apt install graphviz lcov
          pip install -r requirements.txt
          pip install torch==2.2.2

      # Configure and build
      - name: Configure documentation
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=Coverage \
            -DCMAKE_UNITY_BUILD=ON \
            -DNEML2_TESTS=ON \
            -DNEML2_UNIT=ON \
            -DNEML2_REGRESSION=OFF \
            -DNEML2_VERIFICATION=OFF \
            -DNEML2_RUNNER=OFF \
            -DNEML2_PYBIND=ON \
            -DNEML2_DOC=ON \
            -B build \
            .
      - name: Build documentation
        run: cmake --build build --target html -j 2 --

      # Documentation error checking
      - name: Show build logs for C++ documentation
        run: cat build/doc/doxygen.html.log
      - name: Show build logs for Python documentation
        run: cat build/doc/doxygen.python.log
      - name: Warn about syntax errors
        if: ${{ github.event_name == 'pull_request_target'}}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: build/doc/syntax_error.log
      - name: Error if syntax errors were detected
        run: grep -q "No syntax error" build/doc/syntax_error.log

      # Code coverage
      - name: Build unit tests
        run: cmake --build build --target all -j 2 --
      - name: Code coverage check
        run: |
          build/scripts/coverage.sh
          mv build/coverage build/doc/build/html/

      # Preview PR documentation and coverage
      - name: Deploy preview to GitHub Pages
        if: github.event_name == 'pull_request_target'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/doc/build/html
          target-folder: pr-preview/pr-${{ github.event.number }}
          force: false
      - name: Update comment with preview link
        if: github.event_name == 'pull_request_target'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Documentation preview: <https://applied-material-modeling.github.io/neml2/pr-preview/pr-${{ github.event.number }}>
            Code coverage: <https://applied-material-modeling.github.io/neml2/pr-preview/pr-${{ github.event.number }}/coverage>

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: build/doc/build/html
          clean-exclude: pr-preview/
          force: false
